# Generated by Django 3.1.1 on 2020-09-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='/media/defalt-profile.jpg/', upload_to='profiles'),
        ),
    ]
