# Generated by Django 3.1.1 on 2020-09-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200925_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='defalt-profile.jpg/', upload_to='profiles'),
        ),
    ]
