# Generated by Django 3.1.1 on 2020-09-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200925_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='default-profile.jpg/', upload_to='profiles'),
        ),
    ]
