# Generated by Django 3.1.1 on 2020-09-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200925_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='default-profile.jpg/', upload_to='profiles'),
        ),
    ]
