# Generated by Django 3.1.1 on 2020-10-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200925_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='default-profile.jpg/', upload_to='media'),
        ),
    ]
