# Generated by Django 3.1.1 on 2020-09-29 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0005_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='likes',
        ),
    ]
